source "https://rubygems.org"

gem "cucumber"            # Human Readable Specification by Example
gem "capybara"            # For driving our browsers
gem "poltergeist"         # For headless testing with phantomjs
gem "phantomjs"           # Attempts to install phantom if you don't already have it
gem 'selenium-webdriver'  
gem "childprocess"        # For managing the running Rails and Ember Apps
gem "activesupport"       # For Autoloading model classes like Rails
gem "activerecord"        # Database Access
gem "pg"                  # The Database Used by the Rails App, change as needed
gem "factory_girl"        # For Creating Fixture Data
gem "database_cleaner"    # Clean the Database between runs
gem "rspec-expectations"  # Expectations Library
gem "byebug"              # Ruby 2.0 Debugging
gem "paper_trail", "~> 3.0.6"
gem "pry"
gem 'sass', '~> 3.4.13'