# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0ab2ef2b74cfc3db96ec354243bbcab3657ca75958cfd931f4bf170a43532b71f331bd73d5724153b6dff7b6e5834d0fb069b0ecb6eb31912f9308490deb555
  SSO_CONSUMER_KEY:    ukKjuVekQ6K7Ef2JeujRsw
  SSO_CONSUMER_SECRET: yQ9xpMiESdqYG1xecGpfvQ
  SSO_SITE:            http://sso-stage.si.is.co.za
  SIAUTH_URL:          http://si-auth.si.is.co.za/auth
  SIAUTH_KEY:          eb9d4559b681427ca07f23aca164ac7b

test:
  secret_key_base: 9eb37768a03d0d90ddd77216962e35bb02c7884fdfe81f5907c31afab0af9fc0db5cfd4e108c1d402d8f2007e973d99f65244be8c7a2ff38127cc6eb3d3f7dca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
