source 'https://rubygems.org'

gem 'rails', '4.1.5'

gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'omniauth-is-oauth2', git: 'git@github.com:InternetSolutions/omniauth-is-oauth2'
gem 'pg', '~> 0.17.1'
gem 'puma'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'guard-rspec', require: false
  gem 'spring-commands-rspec'
end

group :development, :test do
  gem 'better_errors', '~> 2.0.0'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'foreman'
  gem 'pry'
  gem 'rspec-rails', '~> 3.1.0'
  gem 'shoulda-matchers', '~> 2.7.0', require: false
  gem 'spring'
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

