source 'https://rubygems.org'

gem 'rails', '4.2.0'

gem 'active_model_serializers', '~> 0.9.2'
gem 'axlsx', '~> 2.0.1'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'omniauth-is-oauth2', git: 'git@github.com:InternetSolutions/omniauth-is-oauth2'
gem 'oj', '~>2.11.1'
gem 'multi_json', '~> 1.10.1'
gem 'pg', '~> 0.17.1'
gem 'puma', '~> 2.11.0'
gem 'paper_trail', '~> 3.0.6'
gem 'rest-client', '~> 1.7.2'
gem 'faraday', '~> 0.9.1'
gem 'sqlite3'
gem 'sass', '~> 3.4.13'
gem 'uglifier', '>= 1.3.0'
gem "sentry-raven"
gem 'processmaker', :git => 'git@github.com:vmpj/processmaker_gem.git'

group :development do
  gem 'guard-rspec', require: false
  gem 'nokogiri', '~> 1.6.6.1'
  gem 'spring-commands-rspec'
end

group :development, :test do
  gem 'awesome_print', '~> 1.6.1'
  gem 'better_errors', '~> 2.0.0'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'foreman'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.1.0'
  gem 'shoulda-matchers', '~> 2.7.0', require: false
  gem 'spring'
  gem 'simplecov-rcov', :require => false, :group => :test
  gem 'ci_reporter_rspec', '~> 1.0.0'
  gem 'webmock', '~> 1.20.4'
  gem 'vcr', '~> 2.9.3'

end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

