source 'https://rubygems.org'

gem 'rails', '4.2.0'

gem 'active_model_serializers', '~> 0.9.2'
gem 'axlsx', '~> 2.0.1'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'omniauth-is-oauth2', git: 'https://04947d41c258e7f2cae2a8d13f3d69f1d3b428fd:x-oauth-basic@github.com/InternetSolutions/omniauth-is-oauth2.git'
gem 'oj', '~>2.11.1'
gem 'pg', '~> 0.17.1'
gem 'puma', '2.11.1'
gem 'paper_trail', '~> 3.0.6'
gem 'rest-client', '~> 1.7.2'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem "sentry-raven"
gem 'ci_reporter_rspec', '~> 1.0.0'

group :production do
  gem 'unicorn'
end

group :development do
  gem 'guard-rspec', require: false
  gem 'nokogiri', '~> 1.6.6.1'
  gem 'spring-commands-rspec'
end

group :development, :test do
  gem 'sqlite3'
  gem 'awesome_print', '~> 1.6.1'
  gem 'better_errors', '~> 2.0.0'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'foreman'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.1.0'
  gem 'shoulda-matchers', '~> 2.7.0', require: false
  gem 'spring'
  gem 'simplecov-rcov', :require => false, :group => :test
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

